#
# rs485_bricklet
#
"xconfig": {
    "config_func": ["Write Low Level", "Read Low Level", "Set RS485 Configuration", "Set Modbus Configuration", "Set Mode", "Set Communication LED Config", "Set Error LED Config", "Set Buffer Config", "Modbus Slave Report Exception", "Modbus Slave Answer Read Coils Request Low Level", "Modbus Master Read Coils", "Modbus Slave Answer Read Holding Registers Request Low Level", "Modbus Master Read Holding Registers", "Modbus Slave Answer Write Single Coil Request", "Modbus Master Write Single Coil", "Modbus Slave Answer Write Single Register Request", "Modbus Master Write Single Register", "Modbus Slave Answer Write Multiple Coils Request", "Modbus Master Write Multiple Coils Low Level", "Modbus Slave Answer Write Multiple Registers Request", "Modbus Master Write Multiple Registers Low Level", "Modbus Slave Answer Read Discrete Inputs Request Low Level", "Modbus Master Read Discrete Inputs", "Modbus Slave Answer Read Input Registers Request Low Level", "Modbus Master Read Input Registers", "Set Status LED Config"],
    "setter_func": ["Write Low Level", "Read Low Level", "Set RS485 Configuration", "Set Modbus Configuration", "Set Mode", "Set Communication LED Config", "Set Error LED Config", "Set Buffer Config", "Modbus Slave Report Exception", "Modbus Slave Answer Read Coils Request Low Level", "Modbus Master Read Coils", "Modbus Slave Answer Read Holding Registers Request Low Level", "Modbus Master Read Holding Registers", "Modbus Slave Answer Write Single Coil Request", "Modbus Master Write Single Coil", "Modbus Slave Answer Write Single Register Request", "Modbus Master Write Single Register", "Modbus Slave Answer Write Multiple Coils Request", "Modbus Master Write Multiple Coils Low Level", "Modbus Slave Answer Write Multiple Registers Request", "Modbus Master Write Multiple Registers Low Level", "Modbus Slave Answer Read Discrete Inputs Request Low Level", "Modbus Master Read Discrete Inputs", "Modbus Slave Answer Read Input Registers Request Low Level", "Modbus Master Read Input Registers", "Set Status LED Config"],
    "getter_func": ["Enable Read Callback", "Disable Read Callback", "Is Read Callback Enabled", "Get RS485 Configuration", "Get Modbus Configuration", "Get Mode", "Get Communication LED Config", "Get Error LED Config", "Get Buffer Config", "Get Buffer Status", "Enable Error Count Callback", "Disable Error Count Callback", "Is Error Count Callback Enabled", "Get Modbus Common Error Count", "Get SPITFP Error Count", "Get Status LED Config", "Get Identity"],
    "callbacks": ["Read Low Level", "Error Count", "Modbus Slave Read Coils Request", "Modbus Master Read Coils Response Low Level", "Modbus Slave Read Holding Registers Request", "Modbus Master Read Holding Registers Response Low Level", "Modbus Slave Write Single Coil Request", "Modbus Master Write Single Coil Response", "Modbus Slave Write Single Register Request", "Modbus Master Write Single Register Response", "Modbus Slave Write Multiple Coils Request Low Level", "Modbus Master Write Multiple Coils Response", "Modbus Slave Write Multiple Registers Request Low Level", "Modbus Master Write Multiple Registers Response", "Modbus Slave Read Discrete Inputs Request", "Modbus Master Read Discrete Inputs Response Low Level", "Modbus Slave Read Input Registers Request", "Modbus Master Read Input Registers Response Low Level"]
}

